# Generated by Django 3.1.2 on 2024-03-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(max_length=255)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Collaborateurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_option', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cout_additionnel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Option',
            },
        ),
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditions', models.TextField()),
            ],
            options={
                'db_table': 'Prestation',
            },
        ),
        migrations.CreateModel(
            name='Formules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titre', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.option')),
            ],
            options={
                'db_table': 'Formules',
            },
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benifice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.collaborateurs')),
                ('formules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.formules')),
            ],
            options={
                'db_table': 'Evenements',
            },
        ),
    ]
