# Generated by Django 3.1.2 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenements',
            name='horaires',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
