# Generated by Django 3.1.2 on 2024-03-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_evenements_horaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenements',
            name='collaborateur',
        ),
        migrations.CreateModel(
            name='EventColaborateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evenements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.evenements')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.collaborateurs')),
            ],
            options={
                'db_table': 'EventColaborateur',
            },
        ),
    ]
