# Generated by Django 3.1.2 on 2024-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_paitent',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.IntegerField(default=0),
        ),
    ]
